nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: L'API BileMo vous permet d'accèder à notre catalogue de téléphones disponible à la vente.</br> Elle vous permet aussi de gérer vos clients.
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas:
        default:
            path_patterns: [ ^/api ]
        admin:
            path_patterns: [ ^/admin/api ]
