#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /api/register
  controller: App\Controller\AuthController::register
  methods: POST

login_check:
  path: /api/login_check
  methods:  [POST]

app.swagger_ui:
  path: /api/doc/{area}
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }